### ISSUE TITLE
Obsolete xlsxwriter dependency

### ISSUE THREAD

**Issue by adrienjacob** [it-is-me-mario/MARIO#34]
I see the package depency states "xlsxwriter <= 1.3.7", whereas the current version is 3.0.3... Is this really required?
When installing the package, it downgraded my package version, and broke functionnalities with other Python scripts I'm running.
Thanks in advance...

**Comment by mohammadamint** [comment]
@adrienjacob 

Thanks for notifying the issue, 
will be taken care of in the upcoming release.
