### ISSUE TITLE
Updating the license

### ISSUE THREAD

**Issue by nigolred** [it-is-me-mario/MARIO#41]

**Comment by mohammadamint** [comment]
The Creative Commons licenses are not remotely suitable for software.  Anything with non-commercial is automatically not open too.
CC‑BY‑NC‑SA‑4.0 doesn't give users the rights they need to run code.
MIT and Apache‑2.0 are good permissive choices, while GPL‑3.0‑or‑later and AGPL‑3.0‑or‑later are good copyleft choices.  There is an increasing tendency to use permissive licenses these days, for simplicity, if nothing else.
Spin off businesses might be advised to select the AGPL‑3.0‑or‑later license for greater protection — such that others will need to convey their modifications on request if they distribute binaries or offer SaaS architectures.
