### ISSUE TITLE
Docs show old name of sut_to_iot (i.e., to_iot)

### ISSUE THREAD

**Issue by nigolred** [it-is-me-mario/MARIO#42]
The doc is presenting to_iot as a name. The function name is actually sut_to_iot

https://mario-suite.readthedocs.io/en/latest/api_document/mario.Database.to_iot.html#mario.Database.to_iot

**Comment by mohammadamint** [comment]
the issue will be solved in the upcoming release as the name of the function is changed to "to_iot" in the new version. the word "sut" was redundant in the name of the function (as only a sut can be converted to iot)
