### ISSUE TITLE
Database.aggregate function bug in case of multiple scenarios 

### ISSUE THREAD

**Issue by LorenzoRinaldi** [it-is-me-mario/MARIO#63]
In case you build a database with multiple scenarios where only coefficient matrices are present (only 'z','v','e' and not 'Z','V','E') the function returns an error. In fact, the initial calc_all is checking the presence of 'Z','V' and 'E' just for the baseline scenario. 

To solve it, is enough to enclose the calc all in a for loop iterating on self.scenarios.

**Comment by mohammadamint** [comment]
I belive that is already the case in the aggregate fuction. Could you please provide the example that you run and face the issue?
