### ISSUE TITLE
parse_exiobase bug when passing Exiobase hybrid folder

### ISSUE THREAD

**Issue by nigolred** [it-is-me-mario/MARIO#66]
I guess something went wrong in our attempt to create a single function for all databases in the Exiobase family. I am trying to use it to import the hybrid version:

```
path = C:/Users/nicog/Politecnico di Milano/DENG-SESAM - Documenti/DATASETS/Exiobase Hybrid 3.3.18
World = mario.parse_exiobase(path=path, unit='Hybrid', table='SUT')
```

Got this error:
`TypeError: type object got multiple values for keyword argument 'year'
`

I worked around by using the dedicated parsing function:
`World = mario.hybrid_sut_exiobase(path, extensions=["resource","Land","Emiss",])`

**Comment by mohammadamint** [comment]
fixed thorugh pr #70
